/*------------------------------------------------------------------------------
 *  \file  OR_Conversion.cpp
 *  \brief Implementation of class OR_Conversion
 *  \author Gabriel Peyré 2001-07-08
 *------------------------------------------------------------------------------*/

#ifdef OR_SCCSID
static const char* sccsid = "@(#) OR_Conversion.cpp (c) Gabriel Peyré & Antoine Bouthors 2001";
#endif // OR_SCCSID


#include "../stdafx.h"
#include "OR_Conversion.h"



using namespace OR;

/** a macro to implement the 2 convertion functions */
#define IMPL_CONV(type, code_string2type, code_type2string)						\
type OR_Conversion::StringTo_##type(OR_String& str)								\
{	code_string2type															\
	return (type) OR_ERROR; }													\
OR_String OR_Conversion::type##_ToString(type val)								\
{	code_type2string															\
	return OR_String("Error in OR_Conversion::" #type "_ToString." ); }
/** a macro to make a test for convertion from string to enum */
#define IMPL_STR2TYPE(type)						\
	if( str==#type ) return type
/** a macro to make a test for convertion from enum to string */
#define IMPL_TYPE2STR(type)						\
	if( val==type ) return OR_String(#type);


IMPL_CONV(OR_VIEWPORT_Type,
	IMPL_STR2TYPE(OR_VIEWPORT_Screen);
	IMPL_STR2TYPE(OR_VIEWPORT_FeedBack);
	IMPL_STR2TYPE(OR_VIEWPORT_Undefined);
	,
	IMPL_TYPE2STR(OR_VIEWPORT_Screen);
	IMPL_TYPE2STR(OR_VIEWPORT_FeedBack);
	IMPL_TYPE2STR(OR_VIEWPORT_Undefined);
	)

IMPL_CONV(OR_LENSFLARE_Type,
	IMPL_STR2TYPE(OR_LENSFLARE_Infinite);
	IMPL_STR2TYPE(OR_LENSFLARE_Local);
	IMPL_STR2TYPE(OR_LENSFLARE_Undefined);
	,
	IMPL_TYPE2STR(OR_LENSFLARE_Infinite);
	IMPL_TYPE2STR(OR_LENSFLARE_Local);
	IMPL_TYPE2STR(OR_LENSFLARE_Undefined);
)

IMPL_CONV(OR_Culling_Mode,
	IMPL_STR2TYPE(OR_Culling_Front);
	IMPL_STR2TYPE(OR_Culling_Back);
	IMPL_STR2TYPE(OR_Culling_None);
	IMPL_STR2TYPE(OR_Culling_Undefined);
	,
	IMPL_TYPE2STR(OR_Culling_Front);
	IMPL_TYPE2STR(OR_Culling_Back);
	IMPL_TYPE2STR(OR_Culling_None);
	IMPL_TYPE2STR(OR_Culling_Undefined);
)

IMPL_CONV(OR_Drawing_Mode,
	IMPL_STR2TYPE(OR_Drawing_Filled);
	IMPL_STR2TYPE(OR_Drawing_Wireframe);
	IMPL_STR2TYPE(OR_Drawing_Point);
	,
	IMPL_TYPE2STR(OR_Drawing_Filled);
	IMPL_TYPE2STR(OR_Drawing_Wireframe);
	IMPL_TYPE2STR(OR_Drawing_Point);
)


IMPL_CONV(OR_Blending_Mode,
	IMPL_STR2TYPE(OR_Blending_SrcA_1MinusSrcA);
	IMPL_STR2TYPE(OR_Blending_SrcA_1);
	IMPL_STR2TYPE(OR_Blending_SrcA_0);
	IMPL_STR2TYPE(OR_Blending_1_1);
	IMPL_STR2TYPE(OR_Blending_None);
	IMPL_STR2TYPE(OR_Blending_Undefined);
	,
	IMPL_TYPE2STR(OR_Blending_SrcA_1MinusSrcA);
	IMPL_TYPE2STR(OR_Blending_SrcA_1);
	IMPL_TYPE2STR(OR_Blending_SrcA_0);
	IMPL_TYPE2STR(OR_Blending_1_1);
	IMPL_TYPE2STR(OR_Blending_None);
	IMPL_TYPE2STR(OR_Blending_Undefined);
)

IMPL_CONV(OR_ANIMATION_Evaluator_Type,
	IMPL_STR2TYPE(OR_ANIMATION_Evaluator_Linear);
	IMPL_STR2TYPE(OR_ANIMATION_Evaluator_Bezier);
	IMPL_STR2TYPE(OR_ANIMATION_Evaluator_Constant);
	IMPL_STR2TYPE(OR_ANIMATION_Evaluator_TCB);
	IMPL_STR2TYPE(OR_ANIMATION_Evaluator_Smooth); 
	IMPL_STR2TYPE(OR_ANIMATION_Evaluator_Undefined);
	,
	IMPL_TYPE2STR(OR_ANIMATION_Evaluator_Linear);
	IMPL_TYPE2STR(OR_ANIMATION_Evaluator_Bezier);
	IMPL_TYPE2STR(OR_ANIMATION_Evaluator_Constant);
	IMPL_TYPE2STR(OR_ANIMATION_Evaluator_TCB);
	IMPL_TYPE2STR(OR_ANIMATION_Evaluator_Smooth); 
	IMPL_TYPE2STR(OR_ANIMATION_Evaluator_Undefined);
)

IMPL_CONV(OR_ANIMATION_Track_Type,
	IMPL_STR2TYPE(OR_ANIMATION_Track_Float);
	IMPL_STR2TYPE(OR_ANIMATION_Track_Vector);
	IMPL_STR2TYPE(OR_ANIMATION_Track_Quaternion);
	IMPL_STR2TYPE(OR_ANIMATION_Track_Bool);
	IMPL_STR2TYPE(OR_ANIMATION_Track_Undefined);
	,
	IMPL_TYPE2STR(OR_ANIMATION_Track_Float);
	IMPL_TYPE2STR(OR_ANIMATION_Track_Vector);
	IMPL_TYPE2STR(OR_ANIMATION_Track_Quaternion);
	IMPL_TYPE2STR(OR_ANIMATION_Track_Bool);
	IMPL_TYPE2STR(OR_ANIMATION_Track_Undefined);
)

IMPL_CONV(OR_ANIMATION_Track_Behavior,
	IMPL_STR2TYPE(OR_ANIMATION_Behavior_Constant);
	IMPL_STR2TYPE(OR_ANIMATION_Behavior_Loop);
	IMPL_STR2TYPE(OR_ANIMATION_Behavior_PingPong);
	IMPL_STR2TYPE(OR_ANIMATION_Behavior_RelativeLoop);
	IMPL_STR2TYPE(OR_ANIMATION_Behavior_Undefined);
	,
	IMPL_TYPE2STR(OR_ANIMATION_Behavior_Constant);
	IMPL_TYPE2STR(OR_ANIMATION_Behavior_Loop);
	IMPL_TYPE2STR(OR_ANIMATION_Behavior_PingPong);
	IMPL_TYPE2STR(OR_ANIMATION_Behavior_RelativeLoop);
	IMPL_TYPE2STR(OR_ANIMATION_Behavior_Undefined);
)

IMPL_CONV(OR_ANIMATION_Player_Behavior,
	IMPL_STR2TYPE(OR_ANIMATION_Player_Pause);
	IMPL_STR2TYPE(OR_ANIMATION_Player_Stop);			
	IMPL_STR2TYPE(OR_ANIMATION_Player_Loop);			
	IMPL_STR2TYPE(OR_ANIMATION_Player_PingPong);		
	IMPL_STR2TYPE(OR_ANIMATION_Player_RelativeLoop);	
	IMPL_STR2TYPE(OR_ANIMATION_Player_Undefined);
	,
	IMPL_TYPE2STR(OR_ANIMATION_Player_Pause);
	IMPL_TYPE2STR(OR_ANIMATION_Player_Stop);			
	IMPL_TYPE2STR(OR_ANIMATION_Player_Loop);			
	IMPL_TYPE2STR(OR_ANIMATION_Player_PingPong);		
	IMPL_TYPE2STR(OR_ANIMATION_Player_RelativeLoop);	
	IMPL_TYPE2STR(OR_ANIMATION_Player_Undefined);
)

IMPL_CONV(OR_ANIMATION_Target,
	IMPL_STR2TYPE(OR_ANIMATION_Target_Pos);
	IMPL_STR2TYPE(OR_ANIMATION_Target_PosX);
	IMPL_STR2TYPE(OR_ANIMATION_Target_PosY);
	IMPL_STR2TYPE(OR_ANIMATION_Target_PosZ);
	IMPL_STR2TYPE(OR_ANIMATION_Target_Rot);
	IMPL_STR2TYPE(OR_ANIMATION_Target_Scale);
	IMPL_STR2TYPE(OR_ANIMATION_Target_ScaleX);
	IMPL_STR2TYPE(OR_ANIMATION_Target_ScaleY);
	IMPL_STR2TYPE(OR_ANIMATION_Target_ScaleZ);
	IMPL_STR2TYPE(OR_ANIMATION_Target_Ambient);
	IMPL_STR2TYPE(OR_ANIMATION_Target_AmbientR);
	IMPL_STR2TYPE(OR_ANIMATION_Target_AmbientV);
	IMPL_STR2TYPE(OR_ANIMATION_Target_AmbientB);
	IMPL_STR2TYPE(OR_ANIMATION_Target_Diffuse);
	IMPL_STR2TYPE(OR_ANIMATION_Target_DiffuseR);
	IMPL_STR2TYPE(OR_ANIMATION_Target_DiffuseV);
	IMPL_STR2TYPE(OR_ANIMATION_Target_DiffuseB);
	IMPL_STR2TYPE(OR_ANIMATION_Target_Specular);
	IMPL_STR2TYPE(OR_ANIMATION_Target_SpecularR);
	IMPL_STR2TYPE(OR_ANIMATION_Target_SpecularV);
	IMPL_STR2TYPE(OR_ANIMATION_Target_SpecularB);
	IMPL_STR2TYPE(OR_ANIMATION_Target_Shine);
	IMPL_STR2TYPE(OR_ANIMATION_Target_Display);
	IMPL_STR2TYPE(OR_ANIMATION_Target_Undefined);
	,
	IMPL_TYPE2STR(OR_ANIMATION_Target_Pos);
	IMPL_TYPE2STR(OR_ANIMATION_Target_PosX);
	IMPL_TYPE2STR(OR_ANIMATION_Target_PosY);
	IMPL_TYPE2STR(OR_ANIMATION_Target_PosZ);
	IMPL_TYPE2STR(OR_ANIMATION_Target_Rot);
	IMPL_TYPE2STR(OR_ANIMATION_Target_Scale);
	IMPL_TYPE2STR(OR_ANIMATION_Target_ScaleX);
	IMPL_TYPE2STR(OR_ANIMATION_Target_ScaleY);
	IMPL_TYPE2STR(OR_ANIMATION_Target_ScaleZ);
	IMPL_TYPE2STR(OR_ANIMATION_Target_Ambient);
	IMPL_TYPE2STR(OR_ANIMATION_Target_AmbientR);
	IMPL_TYPE2STR(OR_ANIMATION_Target_AmbientV);
	IMPL_TYPE2STR(OR_ANIMATION_Target_AmbientB);
	IMPL_TYPE2STR(OR_ANIMATION_Target_Diffuse);
	IMPL_TYPE2STR(OR_ANIMATION_Target_DiffuseR);
	IMPL_TYPE2STR(OR_ANIMATION_Target_DiffuseV);
	IMPL_TYPE2STR(OR_ANIMATION_Target_DiffuseB);
	IMPL_TYPE2STR(OR_ANIMATION_Target_Specular);
	IMPL_TYPE2STR(OR_ANIMATION_Target_SpecularR);
	IMPL_TYPE2STR(OR_ANIMATION_Target_SpecularV);
	IMPL_TYPE2STR(OR_ANIMATION_Target_SpecularB);
	IMPL_TYPE2STR(OR_ANIMATION_Target_Shine);
	IMPL_TYPE2STR(OR_ANIMATION_Target_Display);
	IMPL_TYPE2STR(OR_ANIMATION_Target_Undefined);
)

IMPL_CONV(OR_Types ,
	IMPL_STR2TYPE(OR_Shadows);
	IMPL_STR2TYPE(OR_Reflections);
	IMPL_STR2TYPE(OR_FOG_Color); 
	IMPL_STR2TYPE(OR_FOG_Density); 
	IMPL_STR2TYPE(OR_FOG_OnOff);
	IMPL_STR2TYPE(OR_CAMERA_Pos); 
	IMPL_STR2TYPE(OR_CAMERA_DistanceMin);
	IMPL_STR2TYPE(OR_CAMERA_Near); 
	IMPL_STR2TYPE(OR_CAMERA_Far); 
	IMPL_STR2TYPE(OR_CAMERA_Fovy);
	IMPL_STR2TYPE(OR_CAMERA_Aspect);
	IMPL_STR2TYPE(OR_CAMERA_GetType); 
	IMPL_STR2TYPE(OR_CAMERA_Roll);
	IMPL_STR2TYPE(OR_LIGHT_Ambient); 
	IMPL_STR2TYPE(OR_LIGHT_Diffuse); 
	IMPL_STR2TYPE(OR_LIGHT_Specular);
	IMPL_STR2TYPE(OR_LIGHT_Atenuation); 
	IMPL_STR2TYPE(OR_LIGHT_Cutoff); 
	IMPL_STR2TYPE(OR_LIGHT_Exponent);
	IMPL_STR2TYPE(OR_LIGHT_Pos); 
	IMPL_STR2TYPE(OR_LIGHT_Direction); 
	IMPL_STR2TYPE(OR_LIGHT_GlobalAmbient);
	IMPL_STR2TYPE(OR_NURBS_Pos); 
	IMPL_STR2TYPE(OR_NURBS_Axe); 
	IMPL_STR2TYPE(OR_NURBS_Selected_CtrlPt);
	IMPL_STR2TYPE(OR_NURBS_Fill);
	IMPL_STR2TYPE(OR_MESH_Pos); 
	IMPL_STR2TYPE(OR_PARTICULES_Debit); 
	IMPL_STR2TYPE(OR_PARTICULES_EnergyStart); 
	IMPL_STR2TYPE(OR_PARTICULES_EnergyStartVariance); 
	IMPL_STR2TYPE(OR_PARTICULES_EnergyLost); 
	IMPL_STR2TYPE(OR_PARTICULES_EnergyLostVariance); 
	IMPL_STR2TYPE(OR_PARTICULES_Mass);
	IMPL_STR2TYPE(OR_PARTICULES_MassVariance); 
	IMPL_STR2TYPE(OR_PARTICULES_SourcePos); 
	IMPL_STR2TYPE(OR_PARTICULES_InitialSpeed);	 
	IMPL_STR2TYPE(OR_PARTICULES_MaxRadius); 
	IMPL_STR2TYPE(OR_PARTICULES_NbMaxParticules);
	IMPL_STR2TYPE(OR_PARTICULES_EmissionVariance);
	IMPL_STR2TYPE(OR_PARTICULES_StartColor); 
	IMPL_STR2TYPE(OR_PARTICULES_EndColor);
	IMPL_STR2TYPE(OR_PARTICULES_IsSourceActive);
	IMPL_STR2TYPE(OR_PARTICULES_IsSystemActive);
	IMPL_STR2TYPE(OR_PARTICULES_Bounce);
	IMPL_STR2TYPE(OR_META_ENV_Precision); 
	IMPL_STR2TYPE(OR_META_ENV_IsoLevel);
	IMPL_STR2TYPE(OR_SHADER_Ambient); 
	IMPL_STR2TYPE(OR_SHADER_Diffuse); 
	IMPL_STR2TYPE(OR_SHADER_Emission); 
	IMPL_STR2TYPE(OR_SHADER_Specular); 
	IMPL_STR2TYPE(OR_SHADER_Shine); 
	IMPL_STR2TYPE(OR_SHADER_Alpha);
	IMPL_STR2TYPE(OR_SHADER_BorderWidth);
	IMPL_STR2TYPE(OR_SHADER_GetType);
	IMPL_STR2TYPE(OR_FORCE_Type); 
	IMPL_STR2TYPE(OR_FORCE_Pos); 
	IMPL_STR2TYPE(OR_FORCE_Equation);
	IMPL_STR2TYPE(OR_FORCE_DistMax);
	IMPL_STR2TYPE(OR_GIZMO_Dim); 
	IMPL_STR2TYPE(OR_GIZMO_Bounce);
	IMPL_STR2TYPE(OR_GIZMO_Intensity); 
	IMPL_STR2TYPE(OR_GIZMO_InfluenceRadius); 
	IMPL_STR2TYPE(OR_VIEWPORT_Priority); 
	IMPL_STR2TYPE(OR_VIEWPORT_UsePerCent);
	IMPL_STR2TYPE(OR_VIEWPORT_Color);
	IMPL_STR2TYPE(OR_Nb_CAMERA);
	IMPL_STR2TYPE(OR_Nb_MESH); 
	IMPL_STR2TYPE(OR_Nb_NURBS); 
	IMPL_STR2TYPE(OR_Nb_PLAN); 
	IMPL_STR2TYPE(OR_Nb_LIGHT);
	IMPL_STR2TYPE(OR_Nb_PARTICULES_SYSTEM);
	IMPL_STR2TYPE(OR_Nb_MATHS_SURFACE);
	IMPL_STR2TYPE(OR_Nb_META_ENV); 
	IMPL_STR2TYPE(OR_Nb_METABALL);
	IMPL_STR2TYPE(OR_Nb_SHADER);
	IMPL_STR2TYPE(OR_Nb_FORCE); 
	IMPL_STR2TYPE(OR_Nb_PARTICULES_FORCE);
	IMPL_STR2TYPE(OR_Nb_GIZMO); 
	IMPL_STR2TYPE(OR_Nb_PARTICULES_GIZMO);
	IMPL_STR2TYPE(OR_Nb_VIEWPORT);
	IMPL_STR2TYPE(OR_Nb_TEXTURE);
	IMPL_STR2TYPE(OR_Selected_CAMERA); 
	IMPL_STR2TYPE(OR_Selected_LIGHT); 
	IMPL_STR2TYPE(OR_Selected_PLAN);
	IMPL_STR2TYPE(OR_Selected_NURBS); 
	IMPL_STR2TYPE(OR_Selected_MESH);
	IMPL_STR2TYPE(OR_Selected_PARTICULES_SYSTEM);
	IMPL_STR2TYPE(OR_Selected_MATHS_SURFACE);
	IMPL_STR2TYPE(OR_Selected_META_ENV); 
	IMPL_STR2TYPE(OR_Selected_METABALL);
	IMPL_STR2TYPE(OR_Selected_SHADER);
	IMPL_STR2TYPE(OR_Selected_FORCE); 
	IMPL_STR2TYPE(OR_Selected_PARTICULES_FORCE);
	IMPL_STR2TYPE(OR_Selected_GIZMO); 
	IMPL_STR2TYPE(OR_Selected_PARTICULES_GIZMO);
	IMPL_STR2TYPE(OR_Selected_VIEWPORT);
	IMPL_STR2TYPE(OR_Selected_TEXTURE);
	IMPL_STR2TYPE(OR_MATH_SURFACE_OnOff); 
	IMPL_STR2TYPE(OR_LIGHT_OnOff);
	IMPL_STR2TYPE(OR_MESH_OnOff); 
	IMPL_STR2TYPE(OR_GIZMO_OnOff);
	IMPL_STR2TYPE(OR_CAMERA_OnOff); 
	IMPL_STR2TYPE(OR_META_ENV_OnOff);
	, 
	IMPL_TYPE2STR(OR_Shadows);
	IMPL_TYPE2STR(OR_Reflections);
	IMPL_TYPE2STR(OR_FOG_Color); 
	IMPL_TYPE2STR(OR_FOG_Density); 
	IMPL_TYPE2STR(OR_FOG_OnOff);
	IMPL_TYPE2STR(OR_CAMERA_Pos); 
	IMPL_TYPE2STR(OR_CAMERA_DistanceMin);
	IMPL_TYPE2STR(OR_CAMERA_Near); 
	IMPL_TYPE2STR(OR_CAMERA_Far); 
	IMPL_TYPE2STR(OR_CAMERA_Fovy);
	IMPL_TYPE2STR(OR_CAMERA_Aspect);
	IMPL_TYPE2STR(OR_CAMERA_GetType); 
	IMPL_TYPE2STR(OR_CAMERA_Roll);
	IMPL_TYPE2STR(OR_LIGHT_Ambient); 
	IMPL_TYPE2STR(OR_LIGHT_Diffuse); 
	IMPL_TYPE2STR(OR_LIGHT_Specular);
	IMPL_TYPE2STR(OR_LIGHT_Atenuation); 
	IMPL_TYPE2STR(OR_LIGHT_Cutoff); 
	IMPL_TYPE2STR(OR_LIGHT_Exponent);
	IMPL_TYPE2STR(OR_LIGHT_Pos); 
	IMPL_TYPE2STR(OR_LIGHT_Direction); 
	IMPL_TYPE2STR(OR_LIGHT_GlobalAmbient);
	IMPL_TYPE2STR(OR_NURBS_Pos); 
	IMPL_TYPE2STR(OR_NURBS_Axe); 
	IMPL_TYPE2STR(OR_NURBS_Selected_CtrlPt);
	IMPL_TYPE2STR(OR_NURBS_Fill);
	IMPL_TYPE2STR(OR_MESH_Pos); 
	IMPL_TYPE2STR(OR_PARTICULES_Debit); 
	IMPL_TYPE2STR(OR_PARTICULES_EnergyStart); 
	IMPL_TYPE2STR(OR_PARTICULES_EnergyStartVariance); 
	IMPL_TYPE2STR(OR_PARTICULES_EnergyLost); 
	IMPL_TYPE2STR(OR_PARTICULES_EnergyLostVariance); 
	IMPL_TYPE2STR(OR_PARTICULES_Mass);
	IMPL_TYPE2STR(OR_PARTICULES_MassVariance); 
	IMPL_TYPE2STR(OR_PARTICULES_SourcePos); 
	IMPL_TYPE2STR(OR_PARTICULES_InitialSpeed);	 
	IMPL_TYPE2STR(OR_PARTICULES_MaxRadius); 
	IMPL_TYPE2STR(OR_PARTICULES_NbMaxParticules);
	IMPL_TYPE2STR(OR_PARTICULES_EmissionVariance);
	IMPL_TYPE2STR(OR_PARTICULES_StartColor); 
	IMPL_TYPE2STR(OR_PARTICULES_EndColor);
	IMPL_TYPE2STR(OR_PARTICULES_IsSourceActive);
	IMPL_TYPE2STR(OR_PARTICULES_IsSystemActive);
	IMPL_TYPE2STR(OR_PARTICULES_Bounce);
	IMPL_TYPE2STR(OR_META_ENV_Precision); 
	IMPL_TYPE2STR(OR_META_ENV_IsoLevel);
	IMPL_TYPE2STR(OR_SHADER_Ambient); 
	IMPL_TYPE2STR(OR_SHADER_Diffuse); 
	IMPL_TYPE2STR(OR_SHADER_Emission); 
	IMPL_TYPE2STR(OR_SHADER_Specular); 
	IMPL_TYPE2STR(OR_SHADER_Shine); 
	IMPL_TYPE2STR(OR_SHADER_Alpha);
	IMPL_TYPE2STR(OR_SHADER_BorderWidth);
	IMPL_TYPE2STR(OR_SHADER_GetType);
	IMPL_TYPE2STR(OR_FORCE_Type); 
	IMPL_TYPE2STR(OR_FORCE_Pos); 
	IMPL_TYPE2STR(OR_FORCE_Equation);
	IMPL_TYPE2STR(OR_FORCE_DistMax);
	IMPL_TYPE2STR(OR_GIZMO_Dim); 
	IMPL_TYPE2STR(OR_GIZMO_Bounce);
	IMPL_TYPE2STR(OR_GIZMO_Intensity); 
	IMPL_TYPE2STR(OR_GIZMO_InfluenceRadius); 
	IMPL_TYPE2STR(OR_VIEWPORT_Priority); 
	IMPL_TYPE2STR(OR_VIEWPORT_UsePerCent);
	IMPL_TYPE2STR(OR_VIEWPORT_Color);
	IMPL_TYPE2STR(OR_Nb_CAMERA);
	IMPL_TYPE2STR(OR_Nb_MESH); 
	IMPL_TYPE2STR(OR_Nb_NURBS); 
	IMPL_TYPE2STR(OR_Nb_PLAN); 
	IMPL_TYPE2STR(OR_Nb_LIGHT);
	IMPL_TYPE2STR(OR_Nb_PARTICULES_SYSTEM);
	IMPL_TYPE2STR(OR_Nb_MATHS_SURFACE);
	IMPL_TYPE2STR(OR_Nb_META_ENV); 
	IMPL_TYPE2STR(OR_Nb_METABALL);
	IMPL_TYPE2STR(OR_Nb_SHADER);
	IMPL_TYPE2STR(OR_Nb_FORCE); 
	IMPL_TYPE2STR(OR_Nb_PARTICULES_FORCE);
	IMPL_TYPE2STR(OR_Nb_GIZMO); 
	IMPL_TYPE2STR(OR_Nb_PARTICULES_GIZMO);
	IMPL_TYPE2STR(OR_Nb_VIEWPORT);
	IMPL_TYPE2STR(OR_Nb_TEXTURE);
	IMPL_TYPE2STR(OR_Selected_CAMERA); 
	IMPL_TYPE2STR(OR_Selected_LIGHT); 
	IMPL_TYPE2STR(OR_Selected_PLAN);
	IMPL_TYPE2STR(OR_Selected_NURBS); 
	IMPL_TYPE2STR(OR_Selected_MESH);
	IMPL_TYPE2STR(OR_Selected_PARTICULES_SYSTEM);
	IMPL_TYPE2STR(OR_Selected_MATHS_SURFACE);
	IMPL_TYPE2STR(OR_Selected_META_ENV); 
	IMPL_TYPE2STR(OR_Selected_METABALL);
	IMPL_TYPE2STR(OR_Selected_SHADER);
	IMPL_TYPE2STR(OR_Selected_FORCE); 
	IMPL_TYPE2STR(OR_Selected_PARTICULES_FORCE);
	IMPL_TYPE2STR(OR_Selected_GIZMO); 
	IMPL_TYPE2STR(OR_Selected_PARTICULES_GIZMO);
	IMPL_TYPE2STR(OR_Selected_VIEWPORT);
	IMPL_TYPE2STR(OR_Selected_TEXTURE);
	IMPL_TYPE2STR(OR_MATH_SURFACE_OnOff); 
	IMPL_TYPE2STR(OR_LIGHT_OnOff);
	IMPL_TYPE2STR(OR_MESH_OnOff); 
	IMPL_TYPE2STR(OR_GIZMO_OnOff);
	IMPL_TYPE2STR(OR_CAMERA_OnOff); 
	IMPL_TYPE2STR(OR_META_ENV_OnOff);
)

IMPL_CONV(OR_Elements ,
 	IMPL_STR2TYPE(OR_MESH); 
	IMPL_STR2TYPE(OR_LIGHT);
	IMPL_STR2TYPE(OR_LIGHT_Target_Spot); 
	IMPL_STR2TYPE(OR_LIGHT_Free_Spot);
	IMPL_STR2TYPE(OR_LIGHT_Target_Direct); 
	IMPL_STR2TYPE(OR_LIGHT_Free_Direct);
	IMPL_STR2TYPE(OR_NURBS);
	IMPL_STR2TYPE(OR_PARTICULES_SYSTEM);
	IMPL_STR2TYPE(OR_LIGHT_Solid); IMPL_STR2TYPE(OR_NURBS_CtrlPt); 
	IMPL_STR2TYPE(OR_CAMERA); 
	IMPL_STR2TYPE(OR_CAMERA_Free); 
	IMPL_STR2TYPE(OR_CAMERA_Target);
	IMPL_STR2TYPE(OR_FOG); 
	IMPL_STR2TYPE(OR_MATH_SURFACE);
	IMPL_STR2TYPE(OR_META_ENV); IMPL_STR2TYPE(OR_METABALL);
	IMPL_STR2TYPE(OR_SURFACE_TESLATOR);
	IMPL_STR2TYPE(OR_SHADER);
	IMPL_STR2TYPE(OR_SHADER_Flat);
	IMPL_STR2TYPE(OR_SHADER_SingleTextureMap); 
	IMPL_STR2TYPE(OR_SHADER_Reflexive);
	IMPL_STR2TYPE(OR_SHADER_Cartoon); 
	IMPL_STR2TYPE(OR_SHADER_Billboard);
	IMPL_STR2TYPE(OR_SHADER_Bump_Emboss); 
	IMPL_STR2TYPE(OR_Shader_Multi);
	IMPL_STR2TYPE(OR_GIZMO); 
	IMPL_STR2TYPE(OR_GIZMO_Sphere); 
	IMPL_STR2TYPE(OR_GIZMO_Cube); 
	IMPL_STR2TYPE(OR_GIZMO_Cylinder);
	IMPL_STR2TYPE(OR_GIZMO_Square); 
	IMPL_STR2TYPE(OR_GIZMO_Vector); 
	IMPL_STR2TYPE(OR_GIZMO_Point);	
	IMPL_STR2TYPE(OR_BONE);
	IMPL_STR2TYPE(OR_PARTICULES_GIZMO);
	IMPL_STR2TYPE(OR_FORCE); IMPL_STR2TYPE(OR_PARTICULES_FORCE);
	IMPL_STR2TYPE(OR_VIEWPORT);
	IMPL_STR2TYPE(OR_EMPTY);
	IMPL_STR2TYPE(OR_LENSFLARE);
	IMPL_STR2TYPE(OR_UNDEFINED);
	IMPL_STR2TYPE(OR_LOCAL_AXES);
	IMPL_STR2TYPE(OR_TRAJECTORIES);
	IMPL_STR2TYPE(OR_SKINNING_BONE);
	IMPL_STR2TYPE(OR_SKIN);
	,
	IMPL_TYPE2STR(OR_MESH); 
	IMPL_TYPE2STR(OR_LIGHT);
	IMPL_TYPE2STR(OR_LIGHT_Target_Spot); 
	IMPL_TYPE2STR(OR_LIGHT_Free_Spot);
	IMPL_TYPE2STR(OR_LIGHT_Target_Direct); 
	IMPL_TYPE2STR(OR_LIGHT_Free_Direct);
	IMPL_TYPE2STR(OR_NURBS);
	IMPL_TYPE2STR(OR_PARTICULES_SYSTEM);
	IMPL_TYPE2STR(OR_LIGHT_Solid); IMPL_TYPE2STR(OR_NURBS_CtrlPt); 
	IMPL_TYPE2STR(OR_CAMERA); 
	IMPL_TYPE2STR(OR_CAMERA_Free); 
	IMPL_TYPE2STR(OR_CAMERA_Target);
	IMPL_TYPE2STR(OR_FOG); 
	IMPL_TYPE2STR(OR_MATH_SURFACE);
	IMPL_TYPE2STR(OR_META_ENV); IMPL_TYPE2STR(OR_METABALL);
	IMPL_TYPE2STR(OR_SURFACE_TESLATOR);
	IMPL_TYPE2STR(OR_SHADER);
	IMPL_TYPE2STR(OR_SHADER_Flat);
	IMPL_TYPE2STR(OR_SHADER_SingleTextureMap); 
	IMPL_TYPE2STR(OR_SHADER_Reflexive);
	IMPL_TYPE2STR(OR_SHADER_Cartoon); 
	IMPL_TYPE2STR(OR_SHADER_Billboard);
	IMPL_TYPE2STR(OR_SHADER_Bump_Emboss); 
	IMPL_TYPE2STR(OR_Shader_Multi);
	IMPL_TYPE2STR(OR_GIZMO); 
	IMPL_TYPE2STR(OR_GIZMO_Sphere); 
	IMPL_TYPE2STR(OR_GIZMO_Cube); 
	IMPL_TYPE2STR(OR_GIZMO_Cylinder);
	IMPL_TYPE2STR(OR_GIZMO_Square); 
	IMPL_TYPE2STR(OR_GIZMO_Vector); 
	IMPL_TYPE2STR(OR_GIZMO_Point);	
	IMPL_TYPE2STR(OR_BONE);
	IMPL_TYPE2STR(OR_PARTICULES_GIZMO);
	IMPL_TYPE2STR(OR_FORCE); IMPL_TYPE2STR(OR_PARTICULES_FORCE);
	IMPL_TYPE2STR(OR_VIEWPORT);
	IMPL_TYPE2STR(OR_EMPTY);
	IMPL_TYPE2STR(OR_LENSFLARE);
	IMPL_TYPE2STR(OR_UNDEFINED);
	IMPL_TYPE2STR(OR_LOCAL_AXES);
	IMPL_TYPE2STR(OR_TRAJECTORIES);
	IMPL_TYPE2STR(OR_SKINNING_BONE);
	IMPL_TYPE2STR(OR_SKIN);
)

IMPL_CONV(OR_ForceType, 
  	IMPL_STR2TYPE(OR_CsteCentral);
	IMPL_STR2TYPE(OR_QuadCentral);
	IMPL_STR2TYPE(OR_CsteOrthoPlanar);
	IMPL_STR2TYPE(OR_QuadOrthoPlanar);
	IMPL_STR2TYPE(OR_ForceGeneral);
	,
	IMPL_TYPE2STR(OR_CsteCentral);
	IMPL_TYPE2STR(OR_QuadCentral);
	IMPL_TYPE2STR(OR_CsteOrthoPlanar);
	IMPL_TYPE2STR(OR_QuadOrthoPlanar);
	IMPL_TYPE2STR(OR_ForceGeneral);
)


IMPL_CONV(OR_META_Type,  
 	IMPL_STR2TYPE(OR_META_Blobby); 
	IMPL_STR2TYPE(OR_META_Quadratic); 
	IMPL_STR2TYPE(OR_META_Undefined);
	,
	IMPL_TYPE2STR(OR_META_Blobby); 
	IMPL_TYPE2STR(OR_META_Quadratic); 
	IMPL_TYPE2STR(OR_META_Undefined);
)

IMPL_CONV(OR_MetaBehaviour, 
 	IMPL_STR2TYPE(OR_MetaStatic); 
	IMPL_STR2TYPE(OR_MetaRotate); 
	IMPL_STR2TYPE(OR_MetaBehaviour_Undefined);
	,
	IMPL_TYPE2STR(OR_MetaStatic); 
	IMPL_TYPE2STR(OR_MetaRotate); 
	IMPL_TYPE2STR(OR_MetaBehaviour_Undefined);
)

IMPL_CONV(OR_MetaNormalType, 
	IMPL_STR2TYPE(OR_FlatNormal); 
	IMPL_STR2TYPE(OR_GradientNormal); 
	IMPL_STR2TYPE(OR_MetaNormalType_Undefined);
	, 
	IMPL_TYPE2STR(OR_FlatNormal); 
	IMPL_TYPE2STR(OR_GradientNormal); 
	IMPL_TYPE2STR(OR_MetaNormalType_Undefined);
)

IMPL_CONV(OR_ScrMode,  
	IMPL_STR2TYPE(OR_Scr_None); 
	IMPL_STR2TYPE(OR_Scr_Config); 
	IMPL_STR2TYPE(OR_Scr_Password); 
	IMPL_STR2TYPE(OR_Scr_Preview); 
	IMPL_STR2TYPE(OR_Scr_Saver); 
	IMPL_STR2TYPE(OR_Scr_Undefined);
	,
	IMPL_TYPE2STR(OR_Scr_None); 
	IMPL_TYPE2STR(OR_Scr_Config); 
	IMPL_TYPE2STR(OR_Scr_Password); 
	IMPL_TYPE2STR(OR_Scr_Preview); 
	IMPL_TYPE2STR(OR_Scr_Saver); 
	IMPL_TYPE2STR(OR_Scr_Undefined);
)

IMPL_CONV(OR_Position,  
	IMPL_STR2TYPE(OR_POS_FRONT ); 
	IMPL_STR2TYPE(OR_POS_BACK ); 
	IMPL_STR2TYPE(OR_POS_LIE ); 
	IMPL_STR2TYPE(OR_POS_CROSS);
	, 
	IMPL_TYPE2STR(OR_POS_FRONT ); 
	IMPL_TYPE2STR(OR_POS_BACK ); 
	IMPL_TYPE2STR(OR_POS_LIE ); 
	IMPL_TYPE2STR(OR_POS_CROSS);
)

IMPL_CONV(OR_BUTTON,
	IMPL_STR2TYPE(OR_BUTTON_LEFT);
	IMPL_STR2TYPE(OR_BUTTON_MIDDLE);
	IMPL_STR2TYPE(OR_BUTTON_RIGHT);
	IMPL_STR2TYPE(OR_WHEEL);
	,
	IMPL_TYPE2STR(OR_BUTTON_LEFT);
	IMPL_TYPE2STR(OR_BUTTON_MIDDLE);
	IMPL_TYPE2STR(OR_BUTTON_RIGHT);
	IMPL_TYPE2STR(OR_WHEEL);
)

IMPL_CONV(OR_BUTTON_STATE,
	IMPL_STR2TYPE(OR_BUTTON_UP);
	IMPL_STR2TYPE(OR_BUTTON_DOWN);
	,
	IMPL_TYPE2STR(OR_BUTTON_UP);
	IMPL_TYPE2STR(OR_BUTTON_DOWN);
)

IMPL_CONV(OR_SOUND_Types,
	IMPL_STR2TYPE(OR_SOUND_2D);
	IMPL_STR2TYPE(OR_SOUND_3D);
	,
	IMPL_TYPE2STR(OR_SOUND_2D);
	IMPL_TYPE2STR(OR_SOUND_3D);
)



#undef IMPL_CONV
#undef IMPL_STR2TYPE
#undef IMPL_TYPE2STR


///////////////////////////////////////////////////////////////////////////////
//  Copyright (C) 2000-2001 The Orion3D Rewiew Board                         // 
//---------------------------------------------------------------------------//
//	This file is under the Orion3D licence.                                  //
//  Refer to orion3d_licence.txt for more details about the Orion3D Licence. //
//---------------------------------------------------------------------------//
//  Ce fichier est soumis a la Licence Orion3D.                              //
//  Se reporter a orion3d_licence.txt pour plus de details sur cette licence.//
///////////////////////////////////////////////////////////////////////////////
//                           END OF FILE                                     //
///////////////////////////////////////////////////////////////////////////////

